### ISSUE TITLE
Model function itself instead of name of it

### ISSUE THREAD

**Issue by ogencoglu** [jmcarpenter2/parfit#4]
It would be more convenient if the function itself is passed such as 

`fitModels(GradientBoostingRegressor(), gbm_paramGrid, X_train, y_train)`

instead of the current syntax which requires the name of the model function, i.e.,

`fitModels(GradientBoostingRegressor, gbm_paramGrid, X_train, y_train)`

This would make trying out _parfit_ easier as one common practice in using sklearn GridSearchCV is to list the classifiers (not the names of the classifiers) and then the parameter space and iterate over them such as

`clfs = [
                BayesianRidge(),
                Lasso(),
                ElasticNet()
]`

Currently, one can not use _clfs_ object as it is not made out of names of the classifiers.

**Comment by TMorville** [comment]
+1

**Comment by jmcarpenter2** [comment]
Issue resolved. Parfit now requires that the model be instantiated e.g. GradientBoostingRegressor()
