### ISSUE TITLE
missing images  in Readme.

### ISSUE THREAD

**Issue by bharathgs** [jmcarpenter2/parfit#5]
`../screenshots/screenshots/best_rf_model_3D.png` path is missing.
could you push that folder? so that the images get displayed properly

**Comment by jmcarpenter2** [comment]
Hi Bharathgs, thanks for pointing this out to me, and for the contribution earlier today! Could you please let me know if it is displaying on your machine now?

**Comment by bharathgs** [comment]
Hi jason, Nope it is not, check the new PR. 
we should put those images in an *Assets* folder and update the relative paths. so that it can be displayed everywhere.
